spring:
  application:
    name: LocationService
  datasource:
    url: jdbc:postgresql://localhost/ecommerce
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false