-- liquibase formatted sql

-- changeset initial-tables:1

create table tbl_user (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    email varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null check (role in ('ADMIN','CUSTOMER')),
    status boolean not null,
    primary key (id)
);

create table product (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    desc varchar(255),
    name varchar(255) not null,
    price float(53) not null,
    quantity integer not null,
    status boolean not null,
    primary key (id)
);

create table wish_list (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id)
);

create table tbl_order (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    user_id bigint not null,
    primary key (id)
);

create table order_product (
    order_id bigint,
    product_id bigint not null,
    primary key (product_id)
);

create table user_wishlist (
    wish_list_id bigint,
    user_id bigint not null,
    primary key (user_id)
);

create table wishlist_product (
    wish_list_id bigint,
    product_id bigint not null,
    primary key (product_id)
);

create index IDXjmivyxk9rmgysrmsqw15lqr5b
   on product (name);

alter table if exists product
   drop constraint if exists UK_jmivyxk9rmgysrmsqw15lqr5b;

alter table if exists product
   add constraint UK_jmivyxk9rmgysrmsqw15lqr5b unique (name);

alter table if exists tbl_user
   drop constraint if exists UK_npn1wf1yu1g5rjohbek375pp1;

alter table if exists tbl_user
   add constraint UK_npn1wf1yu1g5rjohbek375pp1 unique (email);

alter table if exists user_wishlist
   drop constraint if exists UK_2jml9jw4wavkii52u792xurxm;

alter table if exists user_wishlist
   add constraint UK_2jml9jw4wavkii52u792xurxm unique (wish_list_id);

alter table if exists order_product
   add constraint FKgf08vcwig5ya8bqsaf6852g93
   foreign key (order_id)
   references tbl_order;

alter table if exists order_product
   add constraint FKhnfgqyjx3i80qoymrssls3kno
   foreign key (product_id)
   references product;

alter table if exists tbl_order
   add constraint FKhyolniflkctr0p6bp4t8me9vj
   foreign key (user_id)
   references tbl_user;

alter table if exists user_wishlist
   add constraint FKj71oih6n28xyeoxkgfaymjx9q
   foreign key (wish_list_id)
   references wish_list;

alter table if exists user_wishlist
   add constraint FKo1tlhecll7vh55wdf6i4kkgc2
   foreign key (user_id)
   references tbl_user;

alter table if exists wishlist_product
   add constraint FK8cokx00lt6uxdk70noyqdubeo
   foreign key (wish_list_id)
   references wish_list;

alter table if exists wishlist_product
   add constraint FKsqs4r107po6y96en1si6pryx7
   foreign key (product_id)
   references product;